// Generated by CoffeeScript 1.4.0
(function() {
  var nodemailer, util, winston,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  util = require('util');

  winston = require('winston');

  nodemailer = require('nodemailer');

  module.exports = winston.transports.Email = (function(_super) {

    __extends(Email, _super);

    Email.prototype.name = 'email';

    function Email(options) {
      var _this = this;
      if (options == null) {
        options = {};
      }
      Email.__super__.constructor.apply(this, arguments);
      this.to = options.to, this.from = options.from, this.tags = options.tags;
      if (!(this.to && this.from)) {
        throw new Error("Winston-email Specify to and from");
      }
      if (options.tags) {
        this.tags = options.tags.map(function(t) {
          return "[" + t + "] ";
        }).join('');
      }
      this.smtpTransport = nodemailer.createTransport('SMTP', {
        service: options.service,
        auth: {
          user: options.auth.user,
          pass: options.auth.pass
        }
      });
    }

    Email.prototype.log = function(level, msg, meta, cb) {
      var subject, text;
      if (msg == null) {
        msg = '';
      }
      if (this.silent) {
        cb(null, true);
      }
      text = msg.toString();
      subject = "" + (this.tags || '') + "[" + level + "] " + text.slice(0, 51);
      if (meta) {
        text += "\n---\n" + (util.inspect(meta, null, 5));
      }
      return this.smtpTransport.sendMail({
        from: this.from,
        to: this.to,
        subject: subject,
        text: text
      }, cb);
    };

    return Email;

  })(winston.Transport);

}).call(this);
